// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bewbjleikdhrauxaplrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJld2JqbGVpa2RocmF1eGFwbHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTkzNzksImV4cCI6MjA3MjMzNTM3OX0.evsSyyhU6RmEx2o8QRLvVcK_ziRXxyJ-1KbwsyVQow0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});