// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldvpfujxcgothmqubciy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdnBmdWp4Y2dvdGhtcXViY2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5NDkyNzUsImV4cCI6MjA4MjUyNTI3NX0.8CiKyB9VswDTn9NPP7AyrkK2vET-7G8ADIVOUe0SJsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});